### ISSUE TITLE
Documentation API cleanup 

### ISSUE THREAD

**Issue by chseifert** [EEXCESS/eexcess#2]
Is one of the following pages obsolete?

https://github.com/EEXCESS/eexcess/wiki/Request-and-Response-format-for-call-to-federated-recommender-and-privacy-proxy

https://github.com/EEXCESS/eexcess/wiki/json-exchange-format

If so, please delete the obsolete (old) one.

**Comment by mgrani** [comment]
Yes, this one: https://github.com/EEXCESS/eexcess/wiki/json-exchange-format (it is written on top of the page).

**Comment by chseifert** [comment]
Any argument against deleting the page (i did not read the note) and it might confuse future developers.

**Comment by ThomasCerq** [comment]
We can delete it. It's definitely obsolete.

**Comment by chseifert** [comment]
Deleted.
