### ISSUE TITLE
HTTP Status 500 on getDetails Request

### ISSUE THREAD

**Issue by n-witt** [EEXCESS/eexcess#21]
I'm getting an "HTTP Status 500"-[Error](https://github.com/EEXCESS/eexcess/files/27863/err.txt) when sending [this](https://github.com/EEXCESS/eexcess/files/27858/request.txt) request to [this](https://eexcess.joanneum.at/eexcess-privacy-proxy-issuer-1.0-SNAPSHOT/issuer/getDetails) endpoint. As far as I can see the request is conform to [this](https://github.com/EEXCESS/eexcess/wiki/%5B21.09.2015%5D-Request-and-Response-format#pp-details-query-format) format description, aside from the `loggingLevel` attribute, but this is introduced by the APIConnector Module, which is why I assume that this shouldn't be a problem.

Can anyone find the problem here?

**Comment by hziak** [comment]
based minor error in the format -> resolved
