### ISSUE TITLE
Verify logging event was flawlessly received

### ISSUE THREAD

**Issue by n-witt** [EEXCESS/eexcess#23]
This is more a question than an issue:
I'm currently working on the implementation of some logging events using the `sendLog` method from the APIConnector. The code reveals that there are no callbacks in case of success/failure (`xhr.done` and `xhr.fail` not implemented). Now, my question is: Is there a possibility for front end developers to verify whether or not a request was successful?

**Comment by schloett** [comment]
I use the Network inspector of Chrome's DevTools to inspect the ajax requests. If the response is a 200 OK, everything should be fine. If your application requires to determine the status of log requests, please create an issue in C4 and we will integrate them (or if prefer to add them yourself, feel free to do so ;)). The intention of omitting the  callbacks was that there is (almost) no use case, that requires information about the status of the log request.

**Comment by n-witt** [comment]
Okay, I'll do so.
