### ISSUE TITLE
Getting results without title entry

### ISSUE THREAD

**Issue by pstoehr** [EEXCESS/eexcess#27]
We've used the shell scripts provided in the "Getting Started Guide for Client Developers" section of the wiki and generated a recommendation for the keywords different keywords (scripts attached). 

The result set contains entries without a title entry which leads to minor problems in the SECH-Browser. 

Example:
{
        "date": "unknown",
        "description": "Arnim, Harry, Graf; deutscher Botschafter in Paris (1824\u00bf1881); 1 Brief an Prof. R. Hofmann (Wien), Schloss G\u00f6sting, 1879\n",
        "documentBadge": {
                   "id": "3D8A011313D94311B1F90AE62A0AD519",
                    "provider": "Landesarchiv Steiermark",
                    "uri": "http://imdasweb-demo.joanneum.at:8080/archivinformationssystem/rest/record/3d8a0113-13d9-4311-b1f9-0ae62a0ad519"
                },
        "generatingQuery": "field.fulltext.query=paris&field.fulltext.query=history",
        "language": "de",
        "licence": "restricted",
        "mediaType": "text",
        "resultGroup": []
},

We assume that the data provider, in this case the Landesarchiv Steiermark, returns entries without a title and the EEXCESS-recommendation service is just forwarding these entries.

To handle this situation it would be helpful to know which parts of the result entry always exist and which are optional.

Json-Query-Object:
"protectedPartnerList":[
      {
         "systemId":"Landesarchiv Steiermark"
      }
   ],
   "contextKeywords":[
      [
          {
             "text":"Frühmittelalter", 
          }, {
             "text":"Slawen",
          }
      ], [
          {
             "text":"paris", 
          }, {
             "text":"history",
          }
      ], [
          {
             "text":"sport", 
          }, {
             "text":"soccer",
          }
      ]
   ],
   "origin": {
      "clientType": "My super client", 
      "clientVersion": "0.1",
      "module": "curl command line",
      "userID": "9384324107084"
   }
}

Full resultlist:
[res.txt](https://github.com/EEXCESS/eexcess/files/88834/res.txt)

Thanks
Peter

**Comment by hziak** [comment]
thank you, i assign this to @jr-dig-orgel  since he is the person that can most likely resolve this issue

**Comment by jr-dig-orgel** [comment]
Is fixed on our DEV-Server, but the source field is not often filled out.
